import { useEffect } from "react";
import { API_BASE_URL } from "../../../utils/api";

const AnnouncementModal = ({ announcement, onClose, onTagClick }) => {
  useEffect(() => {
    if (announcement) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }

    const handleEscape = (e) => {
      if (e.key === "Escape") onClose();
    };

    document.addEventListener("keydown", handleEscape);

    return () => {
      document.body.style.overflow = "";
      document.removeEventListener("keydown", handleEscape);
    };
  }, [announcement, onClose]);

  if (!announcement) return null;

  return (
    <div className="modal-overlay active" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-top-border"></div>

        <button className="modal-close" onClick={onClose}>
          <svg style={{ width: 20, height: 20 }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
        </button>

        <div className="modal-content">
          <div className="modal-meta-row">
            <span className={`relevance-badge ${announcement.scoreClass}`}>
              Relevance: {announcement.relevanceScore}%
            </span>

            <span>{announcement.category}</span>
            <span>|</span>

            <span>
              {announcement.deadline && (
                <strong className="deadline-text">
                  Due: {announcement.deadline} |{" "}
                </strong>
              )}
              {announcement.date}
            </span>
          </div>

          <div className="ai-marker">Chanakya given Title</div>

          <h2 className="modal-title font-royal">{announcement.aiTitle}</h2>

          <div className="modal-admin-ref">
            Original Reference: "{announcement.adminTitle}"
          </div>

          <div className="modal-section-title">Detected Tags</div>

          <div className="tags-container modal-tags">
            {announcement.tags.map((tag) => (
              <button
                key={tag}
                className="tag-pill"
                onClick={() => onTagClick(tag)}
              >
                {tag}
              </button>
            ))}
          </div>

          <div className="modal-divider"></div>

          <div className="modal-section-title">
            Chanakya Generated Descriptive Summary
          </div>

          <div className="modal-description">{announcement.aiSummary}</div>

          <div className="modal-note">
            * This summary was generated by Chanakya based on the uploaded
            document text.
          </div>

          {announcement.filePath && (
            <div className="view-doc-box">
              <a
                href={`${API_BASE_URL}${announcement.filePath}`}
                target="_blank"
                rel="noreferrer"
                className="view-doc-btn"
              >
                View Original Document
              </a>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AnnouncementModal;

